### ISSUE TITLE
zephir build doesn't create a dll, instead opens configure.js in Notepad++

### ISSUE THREAD

**Issue by ilhanyumer** [phalcon/php-zephir-parser#24]
I'm trying to build a dll file but it doesn't build any dll. I run this command: `zephir build`

Then the output is:
```
Preparing for PHP compilation...
Proparing configuration file...
```
And then it opens the `configure.js` in Notepad++. http://i.imgur.com/vBQiWSn.png And it stays like this forever. If I close the Notepad++ it prints 2 more lines and there is no dll http://i.imgur.com/Hssuc2b.jpg

### Details

* Everything is 64bit
* Zephir Parser => enabled
* Author => Zephir Team and contributors
* Version => 1.0.3
* Build Date => May 13 2017 15:03:23

* PHP 5.6.31 (cli) (built: Jul  5 2017 22:24:47)
* Copyright (c) 1997-2016 The PHP Group
* Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies

* Microsoft Windows [Version 6.3.9600]

* Installation type: installing via package manager

* Visual Studio Ultimate 2012 with Blend
** Blend for Visual Studio
** LightSwitch
** Microsoft Foundation Classes for C++
** Microsoft Office Developer Tools
** Microsoft SharePoint Developer Tools
** Microsoft Web Developer Tools

compile-errors.log:

> Microsoft (R) Program Maintenance Utility Version 11.00.50727.1
> Copyright (C) Microsoft Corporation.  All rights reserved.
> 
> NMAKE : fatal error U1064: MAKEFILE not found and no target specified
> Stop.

The compile.log is empty.

**Comment by sergeyklay** [comment]
It is not the Parser issue. Please open a new issue in the relevant repo: https://github.com/phalcon/zephir
