### ISSUE TITLE
re2c 1.0.2 keeps the initial "/" at the beginning of an docblock (DCOMMENT-Token)

### ISSUE THREAD

**Issue by chilimatic** [phalcon/php-zephir-parser#31]
Hey, 

relates to https://github.com/phalcon/zephir/issues/1591

I got an issue and I cannot pinpoint it, I already solved it but it's a hack. 
I am not sure if even another user is affected, it could just be my setup.

The reason why I put it here an not the zephir compiler is that I didn't want to invest more than 5 hours into reading/debugging the C/C++ and PHP code, esp since I am not used to re2c syntax. 

But first things first.
versions zephir_parser / zephir (i tried different tags with zephir it doesn't matter)
```
zephir parser Tag/v1.1.0
Zephir version 0.10.4-11e39849b0 
```

**lib / program versions**
```
re2c 1.0.2

gcc (GCC) 5.4.0

PHP 7.1.11 (cli) (built: Oct 25 2017 18:30:55) ( NTS )
```

**Error log** _(shortened because it's the same error for all files)_
```
/home/j/development/tools/php/cphalcon/ext/phalcon/exception.zep.c:18:2: error: stray ‘\’ in program
  * Phalcon\Exception
  ^
/home/j/development/tools/php/cphalcon/ext/phalcon/exception.zep.c:18:12: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘Exception’
  * Phalcon\Exception
            ^
/home/j/development/tools/php/cphalcon/ext/phalcon/exception.zep.c:18:12: error: unknown type name ‘Exception’
....
```

The **exception.zep.c compiled source code** so the error is obvious:
```C

#ifdef HAVE_CONFIG_H
#include "../ext_config.h"
#endif

#include <php.h>
#include "../php_ext.h"
#include "../ext.h"

#include <Zend/zend_operators.h>
#include <Zend/zend_exceptions.h>
#include <Zend/zend_interfaces.h>

#include "kernel/main.h"


//**
 * Phalcon\Exception
 *
 * All framework exceptions should use or extend this exception
 */
ZEPHIR_INIT_CLASS(Phalcon_Exception) {

	ZEPHIR_REGISTER_CLASS_EX(Phalcon, Exception, phalcon, exception, zend_exception_get_default(TSRMLS_C), NULL, 0);

	return SUCCESS;

}
``` 
as you can see -> there are two slashes for the doc block comment. 

The scanner keeps the beginning slash in `/**`  for the _DCOMMENT token_ which your compiler does not expect.
 
the hacky fix is pretty simple in zephir/Compilerfile
```php
    /**
     * @param array $topStatement
     */
    public function compileComment(CompilationContext $compilationContext, $topStatement)
    {
        $compilationContext->codePrinter->output('/' . ltrim($topStatement['value'], '/') . '/');
    }
``` 

this does not affect the behaviour and works for me locally but fixing symptoms is not a reasonable approach. 

Since I cannot find anyone else complaining about this I assume this a local setup issue but it's still better to report such behavior than leave it unchecked.

Too me this is a low prio bug esp since I fixed it by a small hack in the compiler.

**Comment by sergeyklay** [comment]
@chilimatic  I've prepared a patch for Zephir Parser to work with re2c >= 1.0. Could you please reinstall Zephir Parser from [**`development`**](https://github.com/phalcon/php-zephir-parser/tree/development) branch?

**Comment by chilimatic** [comment]
@sergeyklay yes ofc I was closely following these changes anyway. :)

**Comment by chilimatic** [comment]
@sergeyklay works fine for me.

**Comment by sergeyklay** [comment]
Fixed in the [latest stable release](https://github.com/phalcon/php-zephir-parser/releases/tag/v1.1.1). Feel free to open a new issue if the problem appears again. Thank you for contributing.
