### ISSUE TITLE
Assembler messages:no such instruction: `shlx %rdx,%rcx,%rdx'

### ISSUE THREAD

**Issue by shiwen5** [phalcon/php-zephir-parser#33]
here is my hardware
1.CentOS release 5.11
2.re2c 0.13.6
3.gcc (GCC) 4.9.4
4.model name      : Intel(R) Xeon(R) CPU E5-2682 v4 @ 2.50GHz
5.PHP 5.6.26 (cli)

**Comment by sergeyklay** [comment]
We'll need the steps to reproduce

**Comment by sergeyklay** [comment]
Did you use **`install`** script from the project root? Could you try to remove `-march=native`  from https://github.com/phalcon/php-zephir-parser/blob/development/install#L53 and try reinstall?

**Comment by shiwen5** [comment]
thank you very much .it's ok! i do that thing
remove -march=native

2017-12-14 3:47 GMT+08:00 Serghei Iakovlev <notifications@github.com>:

**Comment by sergeyklay** [comment]
Refs: https://github.com/phalcon/cphalcon/issues/13143
