### ISSUE TITLE
install error : make: *** No rule to make target '/home/vagrant/phpcode/php-zephir-parser-1.1.2/parser/parser.c', needed by 'parser/parser.lo'.  Stop.

### ISSUE THREAD

**Issue by lvyinhong** [phalcon/php-zephir-parser#38]
php environment is 5.6.32 。  
When I use 7.2.1 I can compile and install. However, an error occurred in 5.6.32
![image](https://user-images.githubusercontent.com/13741530/38854855-68f50a1c-4254-11e8-8d71-fae2755910aa.png)

**Comment by sergeyklay** [comment]
@lvyinhong Is there any logs?

**Comment by sergeyklay** [comment]
I've simplified installation of the extension using standard PHP workflow. Follow these instructions to generate a binary extension for your platform:

```bash
git clone git://github.com/phalcon/php-zephir-parser.git
cd php-zephir-parser
phpize
./configure
make
sudo make install
```

If you have specific PHP versions running:

```bash
git clone git://github.com/phalcon/php-zephir-parser.git
cd php-zephir-parser
/usr/local/bin/phpize
./configure --with-php-config=/usr/local/bin/php-config
make
sudo make install
```

Add the extension to your php.ini:

```ini
[Zephir Parser]
extension=zephir_parser.so
```

These changes already in the `development` branch. I plan release this in the near future.
